# Generated by Django 3.2.4 on 2022-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=350)),
            ],
        ),
    ]
