# Generated by Django 3.2.4 on 2022-04-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0002_bucket_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket_list',
            name='category',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='bucket_list',
            name='item',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='bucket_list',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='bucket_list',
            name='duration',
            field=models.CharField(default='', max_length=350),
        ),
    ]
