# Generated by Django 3.2.4 on 2022-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0003_auto_20220410_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket_list',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
