# Generated by Django 3.2.4 on 2022-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0004_alter_bucket_list_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket_list',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
