# Generated by Django 3.2.4 on 2022-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0005_alter_bucket_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket_list',
            name='bucket_id',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='bucket_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
