# Generated by Django 3.2.4 on 2022-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0006_auto_20220410_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket_list',
            name='location',
            field=models.CharField(default='', max_length=350),
        ),
    ]
