# Generated by Django 3.2.4 on 2022-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0007_bucket_list_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket_list',
            name='status',
            field=models.CharField(default='', max_length=250),
        ),
    ]
