# Generated by Django 3.2.4 on 2022-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0008_bucket_list_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('location', models.CharField(default='', max_length=250)),
                ('contact_number', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
