# Generated by Django 3.2.4 on 2022-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0009_connect_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect_users',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='connect_users',
            name='email',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
