# Generated by Django 3.2.4 on 2022-04-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0012_alter_shared_items_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_items',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
