# Generated by Django 3.2.4 on 2022-04-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('different', '0013_alter_shared_items_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_items',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
